version: '3.9'

services:
  django:
    build: .
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=Blog.settings
      - MYSQL_DATABASE=myblog
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Password@123
      - MYSQL_HOST=mysql  # Use the service name defined in the Docker network
      - MYSQL_PORT=3306
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myblog
      MYSQL_USER: root
      MYSQL_PASSWORD: Password@123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
